import "./globals.css";
import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import localFont from 'next/font/local'
const duneFont = localFont({
    src: '../public/fonts/dunerise.woff2',
    variable: '--font-dune',
})
const interstellarFont = localFont({
    src: '../public/fonts/interstellar.woff2',
    variable: '--font-interstellar',
})

const geologica = Geologica({
    subsets: ['latin'],
    variable: '--font-geologica',
    weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${duneFont.className} ${geologica.className} ${interstellarFont.className} antialiased`}
      >
      <Header />
      <main className="min-h-screen">
        {children}
      </main>
      <Footer />
      </body>
    </html>
  );
}
